//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  settings: Settings;
  settingsConnection: SettingsConnection;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
  philosophy: Philosophy;
  philosophyConnection: PhilosophyConnection;
  therapies: Therapies;
  therapiesConnection: TherapiesConnection;
  bookPage: BookPage;
  bookPageConnection: BookPageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};


export type QueryPhilosophyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPhilosophyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PhilosophyFilter>;
};


export type QueryTherapiesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTherapiesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TherapiesFilter>;
};


export type QueryBookPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBookPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BookPageFilter>;
};

export type DocumentFilter = {
  settings?: InputMaybe<SettingsFilter>;
  homepage?: InputMaybe<HomepageFilter>;
  philosophy?: InputMaybe<PhilosophyFilter>;
  therapies?: InputMaybe<TherapiesFilter>;
  bookPage?: InputMaybe<BookPageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Settings | Homepage | Philosophy | Therapies | BookPage | Folder;

export type Settings = Node & Document & {
  __typename?: 'Settings';
  siteName: Scalars['String']['output'];
  logoImage?: Maybe<Scalars['String']['output']>;
  ctaButtonLabel?: Maybe<Scalars['String']['output']>;
  footerTagline?: Maybe<Scalars['String']['output']>;
  footerCopyright?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  phoneHref?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  addressLine1?: Maybe<Scalars['String']['output']>;
  addressLine2?: Maybe<Scalars['String']['output']>;
  addressCityStateZip?: Maybe<Scalars['String']['output']>;
  mapsUrl?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SettingsFilter = {
  siteName?: InputMaybe<StringFilter>;
  logoImage?: InputMaybe<ImageFilter>;
  ctaButtonLabel?: InputMaybe<StringFilter>;
  footerTagline?: InputMaybe<StringFilter>;
  footerCopyright?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  phoneHref?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  addressLine1?: InputMaybe<StringFilter>;
  addressLine2?: InputMaybe<StringFilter>;
  addressCityStateZip?: InputMaybe<StringFilter>;
  mapsUrl?: InputMaybe<StringFilter>;
};

export type SettingsConnectionEdges = {
  __typename?: 'SettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Settings>;
};

export type SettingsConnection = Connection & {
  __typename?: 'SettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SettingsConnectionEdges>>>;
};

export type HomepageFeatures = {
  __typename?: 'HomepageFeatures';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
};

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  heroEyebrow?: Maybe<Scalars['String']['output']>;
  heroHeadline?: Maybe<Scalars['String']['output']>;
  heroHeadlineEmphasis?: Maybe<Scalars['String']['output']>;
  heroHeadlineSuffix?: Maybe<Scalars['String']['output']>;
  heroSubheading?: Maybe<Scalars['String']['output']>;
  heroCta1Label?: Maybe<Scalars['String']['output']>;
  heroCta2Label?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  heroImageAlt?: Maybe<Scalars['String']['output']>;
  heroBadgeLabelTop?: Maybe<Scalars['String']['output']>;
  heroBadgeLabelBottom?: Maybe<Scalars['String']['output']>;
  featureSectionHeading?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<HomepageFeatures>>>;
  approachImage?: Maybe<Scalars['String']['output']>;
  approachImageAlt?: Maybe<Scalars['String']['output']>;
  approachEyebrow?: Maybe<Scalars['String']['output']>;
  approachHeading?: Maybe<Scalars['String']['output']>;
  approachParagraph1?: Maybe<Scalars['String']['output']>;
  approachParagraph2?: Maybe<Scalars['String']['output']>;
  approachLinkLabel?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomepageFeaturesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type HomepageFilter = {
  heroEyebrow?: InputMaybe<StringFilter>;
  heroHeadline?: InputMaybe<StringFilter>;
  heroHeadlineEmphasis?: InputMaybe<StringFilter>;
  heroHeadlineSuffix?: InputMaybe<StringFilter>;
  heroSubheading?: InputMaybe<StringFilter>;
  heroCta1Label?: InputMaybe<StringFilter>;
  heroCta2Label?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  heroImageAlt?: InputMaybe<StringFilter>;
  heroBadgeLabelTop?: InputMaybe<StringFilter>;
  heroBadgeLabelBottom?: InputMaybe<StringFilter>;
  featureSectionHeading?: InputMaybe<StringFilter>;
  features?: InputMaybe<HomepageFeaturesFilter>;
  approachImage?: InputMaybe<ImageFilter>;
  approachImageAlt?: InputMaybe<StringFilter>;
  approachEyebrow?: InputMaybe<StringFilter>;
  approachHeading?: InputMaybe<StringFilter>;
  approachParagraph1?: InputMaybe<StringFilter>;
  approachParagraph2?: InputMaybe<StringFilter>;
  approachLinkLabel?: InputMaybe<StringFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type Philosophy = Node & Document & {
  __typename?: 'Philosophy';
  heroImage?: Maybe<Scalars['String']['output']>;
  heroImageAlt?: Maybe<Scalars['String']['output']>;
  heroHeadline?: Maybe<Scalars['String']['output']>;
  heroSubtitle?: Maybe<Scalars['String']['output']>;
  missionQuote?: Maybe<Scalars['String']['output']>;
  rootCauseHeading?: Maybe<Scalars['String']['output']>;
  rootCauseParagraph1?: Maybe<Scalars['String']['output']>;
  rootCauseParagraph2?: Maybe<Scalars['String']['output']>;
  rootCauseParagraph3?: Maybe<Scalars['String']['output']>;
  rootCauseImage?: Maybe<Scalars['String']['output']>;
  rootCauseImageAlt?: Maybe<Scalars['String']['output']>;
  overlayProtocolLabel?: Maybe<Scalars['String']['output']>;
  overlayHeadline?: Maybe<Scalars['String']['output']>;
  overlayHeadlineEmphasis?: Maybe<Scalars['String']['output']>;
  overlayBody?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PhilosophyFilter = {
  heroImage?: InputMaybe<ImageFilter>;
  heroImageAlt?: InputMaybe<StringFilter>;
  heroHeadline?: InputMaybe<StringFilter>;
  heroSubtitle?: InputMaybe<StringFilter>;
  missionQuote?: InputMaybe<StringFilter>;
  rootCauseHeading?: InputMaybe<StringFilter>;
  rootCauseParagraph1?: InputMaybe<StringFilter>;
  rootCauseParagraph2?: InputMaybe<StringFilter>;
  rootCauseParagraph3?: InputMaybe<StringFilter>;
  rootCauseImage?: InputMaybe<ImageFilter>;
  rootCauseImageAlt?: InputMaybe<StringFilter>;
  overlayProtocolLabel?: InputMaybe<StringFilter>;
  overlayHeadline?: InputMaybe<StringFilter>;
  overlayHeadlineEmphasis?: InputMaybe<StringFilter>;
  overlayBody?: InputMaybe<StringFilter>;
};

export type PhilosophyConnectionEdges = {
  __typename?: 'PhilosophyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Philosophy>;
};

export type PhilosophyConnection = Connection & {
  __typename?: 'PhilosophyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PhilosophyConnectionEdges>>>;
};

export type TherapiesTherapyList = {
  __typename?: 'TherapiesTherapyList';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  icon?: Maybe<Scalars['String']['output']>;
};

export type Therapies = Node & Document & {
  __typename?: 'Therapies';
  pageHeading?: Maybe<Scalars['String']['output']>;
  pageSubheading?: Maybe<Scalars['String']['output']>;
  cardBlockTitle?: Maybe<Scalars['String']['output']>;
  cardBlockSubtitle?: Maybe<Scalars['String']['output']>;
  ctaBannerImage?: Maybe<Scalars['String']['output']>;
  ctaBannerImageAlt?: Maybe<Scalars['String']['output']>;
  ctaBannerHeadline?: Maybe<Scalars['String']['output']>;
  ctaBannerButtonLabel?: Maybe<Scalars['String']['output']>;
  therapyList?: Maybe<Array<Maybe<TherapiesTherapyList>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TherapiesTherapyListFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type TherapiesFilter = {
  pageHeading?: InputMaybe<StringFilter>;
  pageSubheading?: InputMaybe<StringFilter>;
  cardBlockTitle?: InputMaybe<StringFilter>;
  cardBlockSubtitle?: InputMaybe<StringFilter>;
  ctaBannerImage?: InputMaybe<ImageFilter>;
  ctaBannerImageAlt?: InputMaybe<StringFilter>;
  ctaBannerHeadline?: InputMaybe<StringFilter>;
  ctaBannerButtonLabel?: InputMaybe<StringFilter>;
  therapyList?: InputMaybe<TherapiesTherapyListFilter>;
};

export type TherapiesConnectionEdges = {
  __typename?: 'TherapiesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Therapies>;
};

export type TherapiesConnection = Connection & {
  __typename?: 'TherapiesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TherapiesConnectionEdges>>>;
};

export type BookPage = Node & Document & {
  __typename?: 'BookPage';
  eyebrow?: Maybe<Scalars['String']['output']>;
  heading?: Maybe<Scalars['String']['output']>;
  subheading?: Maybe<Scalars['String']['output']>;
  phoneCardLabel?: Maybe<Scalars['String']['output']>;
  phoneCardSub?: Maybe<Scalars['String']['output']>;
  emailCardLabel?: Maybe<Scalars['String']['output']>;
  emailCardSub?: Maybe<Scalars['String']['output']>;
  addressCardLabel?: Maybe<Scalars['String']['output']>;
  appointmentCardLabel?: Maybe<Scalars['String']['output']>;
  appointmentCardValue?: Maybe<Scalars['String']['output']>;
  appointmentCardSub?: Maybe<Scalars['String']['output']>;
  footerNote?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BookPageFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  subheading?: InputMaybe<StringFilter>;
  phoneCardLabel?: InputMaybe<StringFilter>;
  phoneCardSub?: InputMaybe<StringFilter>;
  emailCardLabel?: InputMaybe<StringFilter>;
  emailCardSub?: InputMaybe<StringFilter>;
  addressCardLabel?: InputMaybe<StringFilter>;
  appointmentCardLabel?: InputMaybe<StringFilter>;
  appointmentCardValue?: InputMaybe<StringFilter>;
  appointmentCardSub?: InputMaybe<StringFilter>;
  footerNote?: InputMaybe<StringFilter>;
};

export type BookPageConnectionEdges = {
  __typename?: 'BookPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<BookPage>;
};

export type BookPageConnection = Connection & {
  __typename?: 'BookPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BookPageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSettings: Settings;
  createSettings: Settings;
  updateHomepage: Homepage;
  createHomepage: Homepage;
  updatePhilosophy: Philosophy;
  createPhilosophy: Philosophy;
  updateTherapies: Therapies;
  createTherapies: Therapies;
  updateBookPage: BookPage;
  createBookPage: BookPage;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationCreateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationUpdatePhilosophyArgs = {
  relativePath: Scalars['String']['input'];
  params: PhilosophyMutation;
};


export type MutationCreatePhilosophyArgs = {
  relativePath: Scalars['String']['input'];
  params: PhilosophyMutation;
};


export type MutationUpdateTherapiesArgs = {
  relativePath: Scalars['String']['input'];
  params: TherapiesMutation;
};


export type MutationCreateTherapiesArgs = {
  relativePath: Scalars['String']['input'];
  params: TherapiesMutation;
};


export type MutationUpdateBookPageArgs = {
  relativePath: Scalars['String']['input'];
  params: BookPageMutation;
};


export type MutationCreateBookPageArgs = {
  relativePath: Scalars['String']['input'];
  params: BookPageMutation;
};

export type DocumentUpdateMutation = {
  settings?: InputMaybe<SettingsMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  philosophy?: InputMaybe<PhilosophyMutation>;
  therapies?: InputMaybe<TherapiesMutation>;
  bookPage?: InputMaybe<BookPageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  settings?: InputMaybe<SettingsMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  philosophy?: InputMaybe<PhilosophyMutation>;
  therapies?: InputMaybe<TherapiesMutation>;
  bookPage?: InputMaybe<BookPageMutation>;
};

export type SettingsMutation = {
  siteName?: InputMaybe<Scalars['String']['input']>;
  logoImage?: InputMaybe<Scalars['String']['input']>;
  ctaButtonLabel?: InputMaybe<Scalars['String']['input']>;
  footerTagline?: InputMaybe<Scalars['String']['input']>;
  footerCopyright?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  phoneHref?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  addressLine1?: InputMaybe<Scalars['String']['input']>;
  addressLine2?: InputMaybe<Scalars['String']['input']>;
  addressCityStateZip?: InputMaybe<Scalars['String']['input']>;
  mapsUrl?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageFeaturesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageMutation = {
  heroEyebrow?: InputMaybe<Scalars['String']['input']>;
  heroHeadline?: InputMaybe<Scalars['String']['input']>;
  heroHeadlineEmphasis?: InputMaybe<Scalars['String']['input']>;
  heroHeadlineSuffix?: InputMaybe<Scalars['String']['input']>;
  heroSubheading?: InputMaybe<Scalars['String']['input']>;
  heroCta1Label?: InputMaybe<Scalars['String']['input']>;
  heroCta2Label?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  heroImageAlt?: InputMaybe<Scalars['String']['input']>;
  heroBadgeLabelTop?: InputMaybe<Scalars['String']['input']>;
  heroBadgeLabelBottom?: InputMaybe<Scalars['String']['input']>;
  featureSectionHeading?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<HomepageFeaturesMutation>>>;
  approachImage?: InputMaybe<Scalars['String']['input']>;
  approachImageAlt?: InputMaybe<Scalars['String']['input']>;
  approachEyebrow?: InputMaybe<Scalars['String']['input']>;
  approachHeading?: InputMaybe<Scalars['String']['input']>;
  approachParagraph1?: InputMaybe<Scalars['String']['input']>;
  approachParagraph2?: InputMaybe<Scalars['String']['input']>;
  approachLinkLabel?: InputMaybe<Scalars['String']['input']>;
};

export type PhilosophyMutation = {
  heroImage?: InputMaybe<Scalars['String']['input']>;
  heroImageAlt?: InputMaybe<Scalars['String']['input']>;
  heroHeadline?: InputMaybe<Scalars['String']['input']>;
  heroSubtitle?: InputMaybe<Scalars['String']['input']>;
  missionQuote?: InputMaybe<Scalars['String']['input']>;
  rootCauseHeading?: InputMaybe<Scalars['String']['input']>;
  rootCauseParagraph1?: InputMaybe<Scalars['String']['input']>;
  rootCauseParagraph2?: InputMaybe<Scalars['String']['input']>;
  rootCauseParagraph3?: InputMaybe<Scalars['String']['input']>;
  rootCauseImage?: InputMaybe<Scalars['String']['input']>;
  rootCauseImageAlt?: InputMaybe<Scalars['String']['input']>;
  overlayProtocolLabel?: InputMaybe<Scalars['String']['input']>;
  overlayHeadline?: InputMaybe<Scalars['String']['input']>;
  overlayHeadlineEmphasis?: InputMaybe<Scalars['String']['input']>;
  overlayBody?: InputMaybe<Scalars['String']['input']>;
};

export type TherapiesTherapyListMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type TherapiesMutation = {
  pageHeading?: InputMaybe<Scalars['String']['input']>;
  pageSubheading?: InputMaybe<Scalars['String']['input']>;
  cardBlockTitle?: InputMaybe<Scalars['String']['input']>;
  cardBlockSubtitle?: InputMaybe<Scalars['String']['input']>;
  ctaBannerImage?: InputMaybe<Scalars['String']['input']>;
  ctaBannerImageAlt?: InputMaybe<Scalars['String']['input']>;
  ctaBannerHeadline?: InputMaybe<Scalars['String']['input']>;
  ctaBannerButtonLabel?: InputMaybe<Scalars['String']['input']>;
  therapyList?: InputMaybe<Array<InputMaybe<TherapiesTherapyListMutation>>>;
};

export type BookPageMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
  subheading?: InputMaybe<Scalars['String']['input']>;
  phoneCardLabel?: InputMaybe<Scalars['String']['input']>;
  phoneCardSub?: InputMaybe<Scalars['String']['input']>;
  emailCardLabel?: InputMaybe<Scalars['String']['input']>;
  emailCardSub?: InputMaybe<Scalars['String']['input']>;
  addressCardLabel?: InputMaybe<Scalars['String']['input']>;
  appointmentCardLabel?: InputMaybe<Scalars['String']['input']>;
  appointmentCardValue?: InputMaybe<Scalars['String']['input']>;
  appointmentCardSub?: InputMaybe<Scalars['String']['input']>;
  footerNote?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsPartsFragment = { __typename: 'Settings', siteName: string, logoImage?: string | null, ctaButtonLabel?: string | null, footerTagline?: string | null, footerCopyright?: string | null, phone?: string | null, phoneHref?: string | null, email?: string | null, addressLine1?: string | null, addressLine2?: string | null, addressCityStateZip?: string | null, mapsUrl?: string | null };

export type HomepagePartsFragment = { __typename: 'Homepage', heroEyebrow?: string | null, heroHeadline?: string | null, heroHeadlineEmphasis?: string | null, heroHeadlineSuffix?: string | null, heroSubheading?: string | null, heroCta1Label?: string | null, heroCta2Label?: string | null, heroImage?: string | null, heroImageAlt?: string | null, heroBadgeLabelTop?: string | null, heroBadgeLabelBottom?: string | null, featureSectionHeading?: string | null, approachImage?: string | null, approachImageAlt?: string | null, approachEyebrow?: string | null, approachHeading?: string | null, approachParagraph1?: string | null, approachParagraph2?: string | null, approachLinkLabel?: string | null, features?: Array<{ __typename: 'HomepageFeatures', title?: string | null, description?: string | null, icon?: string | null } | null> | null };

export type PhilosophyPartsFragment = { __typename: 'Philosophy', heroImage?: string | null, heroImageAlt?: string | null, heroHeadline?: string | null, heroSubtitle?: string | null, missionQuote?: string | null, rootCauseHeading?: string | null, rootCauseParagraph1?: string | null, rootCauseParagraph2?: string | null, rootCauseParagraph3?: string | null, rootCauseImage?: string | null, rootCauseImageAlt?: string | null, overlayProtocolLabel?: string | null, overlayHeadline?: string | null, overlayHeadlineEmphasis?: string | null, overlayBody?: string | null };

export type TherapiesPartsFragment = { __typename: 'Therapies', pageHeading?: string | null, pageSubheading?: string | null, cardBlockTitle?: string | null, cardBlockSubtitle?: string | null, ctaBannerImage?: string | null, ctaBannerImageAlt?: string | null, ctaBannerHeadline?: string | null, ctaBannerButtonLabel?: string | null, therapyList?: Array<{ __typename: 'TherapiesTherapyList', title: string, description: string, icon?: string | null } | null> | null };

export type BookPagePartsFragment = { __typename: 'BookPage', eyebrow?: string | null, heading?: string | null, subheading?: string | null, phoneCardLabel?: string | null, phoneCardSub?: string | null, emailCardLabel?: string | null, emailCardSub?: string | null, addressCardLabel?: string | null, appointmentCardLabel?: string | null, appointmentCardValue?: string | null, appointmentCardSub?: string | null, footerNote?: string | null };

export type SettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SettingsQuery = { __typename?: 'Query', settings: { __typename: 'Settings', id: string, siteName: string, logoImage?: string | null, ctaButtonLabel?: string | null, footerTagline?: string | null, footerCopyright?: string | null, phone?: string | null, phoneHref?: string | null, email?: string | null, addressLine1?: string | null, addressLine2?: string | null, addressCityStateZip?: string | null, mapsUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
}>;


export type SettingsConnectionQuery = { __typename?: 'Query', settingsConnection: { __typename?: 'SettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SettingsConnectionEdges', cursor: string, node?: { __typename: 'Settings', id: string, siteName: string, logoImage?: string | null, ctaButtonLabel?: string | null, footerTagline?: string | null, footerCopyright?: string | null, phone?: string | null, phoneHref?: string | null, email?: string | null, addressLine1?: string | null, addressLine2?: string | null, addressCityStateZip?: string | null, mapsUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, heroEyebrow?: string | null, heroHeadline?: string | null, heroHeadlineEmphasis?: string | null, heroHeadlineSuffix?: string | null, heroSubheading?: string | null, heroCta1Label?: string | null, heroCta2Label?: string | null, heroImage?: string | null, heroImageAlt?: string | null, heroBadgeLabelTop?: string | null, heroBadgeLabelBottom?: string | null, featureSectionHeading?: string | null, approachImage?: string | null, approachImageAlt?: string | null, approachEyebrow?: string | null, approachHeading?: string | null, approachParagraph1?: string | null, approachParagraph2?: string | null, approachLinkLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, features?: Array<{ __typename: 'HomepageFeatures', title?: string | null, description?: string | null, icon?: string | null } | null> | null } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, heroEyebrow?: string | null, heroHeadline?: string | null, heroHeadlineEmphasis?: string | null, heroHeadlineSuffix?: string | null, heroSubheading?: string | null, heroCta1Label?: string | null, heroCta2Label?: string | null, heroImage?: string | null, heroImageAlt?: string | null, heroBadgeLabelTop?: string | null, heroBadgeLabelBottom?: string | null, featureSectionHeading?: string | null, approachImage?: string | null, approachImageAlt?: string | null, approachEyebrow?: string | null, approachHeading?: string | null, approachParagraph1?: string | null, approachParagraph2?: string | null, approachLinkLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, features?: Array<{ __typename: 'HomepageFeatures', title?: string | null, description?: string | null, icon?: string | null } | null> | null } | null } | null> | null } };

export type PhilosophyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PhilosophyQuery = { __typename?: 'Query', philosophy: { __typename: 'Philosophy', id: string, heroImage?: string | null, heroImageAlt?: string | null, heroHeadline?: string | null, heroSubtitle?: string | null, missionQuote?: string | null, rootCauseHeading?: string | null, rootCauseParagraph1?: string | null, rootCauseParagraph2?: string | null, rootCauseParagraph3?: string | null, rootCauseImage?: string | null, rootCauseImageAlt?: string | null, overlayProtocolLabel?: string | null, overlayHeadline?: string | null, overlayHeadlineEmphasis?: string | null, overlayBody?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PhilosophyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PhilosophyFilter>;
}>;


export type PhilosophyConnectionQuery = { __typename?: 'Query', philosophyConnection: { __typename?: 'PhilosophyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PhilosophyConnectionEdges', cursor: string, node?: { __typename: 'Philosophy', id: string, heroImage?: string | null, heroImageAlt?: string | null, heroHeadline?: string | null, heroSubtitle?: string | null, missionQuote?: string | null, rootCauseHeading?: string | null, rootCauseParagraph1?: string | null, rootCauseParagraph2?: string | null, rootCauseParagraph3?: string | null, rootCauseImage?: string | null, rootCauseImageAlt?: string | null, overlayProtocolLabel?: string | null, overlayHeadline?: string | null, overlayHeadlineEmphasis?: string | null, overlayBody?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TherapiesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TherapiesQuery = { __typename?: 'Query', therapies: { __typename: 'Therapies', id: string, pageHeading?: string | null, pageSubheading?: string | null, cardBlockTitle?: string | null, cardBlockSubtitle?: string | null, ctaBannerImage?: string | null, ctaBannerImageAlt?: string | null, ctaBannerHeadline?: string | null, ctaBannerButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, therapyList?: Array<{ __typename: 'TherapiesTherapyList', title: string, description: string, icon?: string | null } | null> | null } };

export type TherapiesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TherapiesFilter>;
}>;


export type TherapiesConnectionQuery = { __typename?: 'Query', therapiesConnection: { __typename?: 'TherapiesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TherapiesConnectionEdges', cursor: string, node?: { __typename: 'Therapies', id: string, pageHeading?: string | null, pageSubheading?: string | null, cardBlockTitle?: string | null, cardBlockSubtitle?: string | null, ctaBannerImage?: string | null, ctaBannerImageAlt?: string | null, ctaBannerHeadline?: string | null, ctaBannerButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, therapyList?: Array<{ __typename: 'TherapiesTherapyList', title: string, description: string, icon?: string | null } | null> | null } | null } | null> | null } };

export type BookPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BookPageQuery = { __typename?: 'Query', bookPage: { __typename: 'BookPage', id: string, eyebrow?: string | null, heading?: string | null, subheading?: string | null, phoneCardLabel?: string | null, phoneCardSub?: string | null, emailCardLabel?: string | null, emailCardSub?: string | null, addressCardLabel?: string | null, appointmentCardLabel?: string | null, appointmentCardValue?: string | null, appointmentCardSub?: string | null, footerNote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BookPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BookPageFilter>;
}>;


export type BookPageConnectionQuery = { __typename?: 'Query', bookPageConnection: { __typename?: 'BookPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BookPageConnectionEdges', cursor: string, node?: { __typename: 'BookPage', id: string, eyebrow?: string | null, heading?: string | null, subheading?: string | null, phoneCardLabel?: string | null, phoneCardSub?: string | null, emailCardLabel?: string | null, emailCardSub?: string | null, addressCardLabel?: string | null, appointmentCardLabel?: string | null, appointmentCardValue?: string | null, appointmentCardSub?: string | null, footerNote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const SettingsPartsFragmentDoc = gql`
    fragment SettingsParts on Settings {
  __typename
  siteName
  logoImage
  ctaButtonLabel
  footerTagline
  footerCopyright
  phone
  phoneHref
  email
  addressLine1
  addressLine2
  addressCityStateZip
  mapsUrl
}
    `;
export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  heroEyebrow
  heroHeadline
  heroHeadlineEmphasis
  heroHeadlineSuffix
  heroSubheading
  heroCta1Label
  heroCta2Label
  heroImage
  heroImageAlt
  heroBadgeLabelTop
  heroBadgeLabelBottom
  featureSectionHeading
  features {
    __typename
    title
    description
    icon
  }
  approachImage
  approachImageAlt
  approachEyebrow
  approachHeading
  approachParagraph1
  approachParagraph2
  approachLinkLabel
}
    `;
export const PhilosophyPartsFragmentDoc = gql`
    fragment PhilosophyParts on Philosophy {
  __typename
  heroImage
  heroImageAlt
  heroHeadline
  heroSubtitle
  missionQuote
  rootCauseHeading
  rootCauseParagraph1
  rootCauseParagraph2
  rootCauseParagraph3
  rootCauseImage
  rootCauseImageAlt
  overlayProtocolLabel
  overlayHeadline
  overlayHeadlineEmphasis
  overlayBody
}
    `;
export const TherapiesPartsFragmentDoc = gql`
    fragment TherapiesParts on Therapies {
  __typename
  pageHeading
  pageSubheading
  cardBlockTitle
  cardBlockSubtitle
  ctaBannerImage
  ctaBannerImageAlt
  ctaBannerHeadline
  ctaBannerButtonLabel
  therapyList {
    __typename
    title
    description
    icon
  }
}
    `;
export const BookPagePartsFragmentDoc = gql`
    fragment BookPageParts on BookPage {
  __typename
  eyebrow
  heading
  subheading
  phoneCardLabel
  phoneCardSub
  emailCardLabel
  emailCardSub
  addressCardLabel
  appointmentCardLabel
  appointmentCardValue
  appointmentCardSub
  footerNote
}
    `;
export const SettingsDocument = gql`
    query settings($relativePath: String!) {
  settings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SettingsParts
  }
}
    ${SettingsPartsFragmentDoc}`;
export const SettingsConnectionDocument = gql`
    query settingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SettingsFilter) {
  settingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SettingsParts
      }
    }
  }
}
    ${SettingsPartsFragmentDoc}`;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export const PhilosophyDocument = gql`
    query philosophy($relativePath: String!) {
  philosophy(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PhilosophyParts
  }
}
    ${PhilosophyPartsFragmentDoc}`;
export const PhilosophyConnectionDocument = gql`
    query philosophyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PhilosophyFilter) {
  philosophyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PhilosophyParts
      }
    }
  }
}
    ${PhilosophyPartsFragmentDoc}`;
export const TherapiesDocument = gql`
    query therapies($relativePath: String!) {
  therapies(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TherapiesParts
  }
}
    ${TherapiesPartsFragmentDoc}`;
export const TherapiesConnectionDocument = gql`
    query therapiesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TherapiesFilter) {
  therapiesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TherapiesParts
      }
    }
  }
}
    ${TherapiesPartsFragmentDoc}`;
export const BookPageDocument = gql`
    query bookPage($relativePath: String!) {
  bookPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BookPageParts
  }
}
    ${BookPagePartsFragmentDoc}`;
export const BookPageConnectionDocument = gql`
    query bookPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BookPageFilter) {
  bookPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BookPageParts
      }
    }
  }
}
    ${BookPagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      settings(variables: SettingsQueryVariables, options?: C): Promise<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}> {
        return requester<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}, SettingsQueryVariables>(SettingsDocument, variables, options);
      },
    settingsConnection(variables?: SettingsConnectionQueryVariables, options?: C): Promise<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}, SettingsConnectionQueryVariables>(SettingsConnectionDocument, variables, options);
      },
    homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      },
    philosophy(variables: PhilosophyQueryVariables, options?: C): Promise<{data: PhilosophyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophyQueryVariables, query: string}> {
        return requester<{data: PhilosophyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophyQueryVariables, query: string}, PhilosophyQueryVariables>(PhilosophyDocument, variables, options);
      },
    philosophyConnection(variables?: PhilosophyConnectionQueryVariables, options?: C): Promise<{data: PhilosophyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophyConnectionQueryVariables, query: string}> {
        return requester<{data: PhilosophyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophyConnectionQueryVariables, query: string}, PhilosophyConnectionQueryVariables>(PhilosophyConnectionDocument, variables, options);
      },
    therapies(variables: TherapiesQueryVariables, options?: C): Promise<{data: TherapiesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TherapiesQueryVariables, query: string}> {
        return requester<{data: TherapiesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TherapiesQueryVariables, query: string}, TherapiesQueryVariables>(TherapiesDocument, variables, options);
      },
    therapiesConnection(variables?: TherapiesConnectionQueryVariables, options?: C): Promise<{data: TherapiesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TherapiesConnectionQueryVariables, query: string}> {
        return requester<{data: TherapiesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TherapiesConnectionQueryVariables, query: string}, TherapiesConnectionQueryVariables>(TherapiesConnectionDocument, variables, options);
      },
    bookPage(variables: BookPageQueryVariables, options?: C): Promise<{data: BookPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookPageQueryVariables, query: string}> {
        return requester<{data: BookPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookPageQueryVariables, query: string}, BookPageQueryVariables>(BookPageDocument, variables, options);
      },
    bookPageConnection(variables?: BookPageConnectionQueryVariables, options?: C): Promise<{data: BookPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookPageConnectionQueryVariables, query: string}> {
        return requester<{data: BookPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookPageConnectionQueryVariables, query: string}, BookPageConnectionQueryVariables>(BookPageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.3/content/dafe0207-2b1b-4cc7-9c6b-fbff72b6740b/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  